[package]
name = "neko"
version = "0.2.0"
authors = ["alihsaas <alihsaas2@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.21"
rustyline = "8.2.0"
rustyline-derive = "0.4.0"
ansi_term = "0.12.1"
